### ISSUE TITLE
Option to use WoW Token Icon instead of "WoW Token" Text

### ISSUE THREAD

**Issue by fr0z3nights** [I-AM-T3X/TokenPriceChecker#1]
I see you're using icons for the price status, whether it has gone up or down, why not use the WoW Token icon instead of the Text WoW Token, it'd make the window smaller and look better,

I replaced the up and down arrows with the following and it shows the WoW Token instead.

Interface\\Icons\\wow_token01
Interface\\Icons\\wow_token02

not that good at coding or I'd just replace it myself, but then when there's an update, yea, anyway just thought it was an idea, could always make it an option between Text and Icon, probably slightly bigger, 20x20, maybe an option to resize.

While talking about options, 
 - would it be possible to also make displaying the up-down arrow able to be turned off or on to make it smaller still, and don't need it
 - the gold display doesn't show the comma, 249388, 249,388, I know a small thing but yeah, when my other gold has it and this doesn't.

Thanks for the addon, whether any of this is implemented or not.

Edit
I did mess with your code, moved the price change icon to where the text "WoW Token" was, and used wow_token01 (colored) for up (and show) and wow_token02 (desaturated) for down, it looks better, it has less of a footprint, and I ended up with this, [16x16](https://1drv.ms/i/s!AiSfe94wb0vWn5QOKxkUNpuYajJ7Hw?e=7FIbvW), was a bit small with this icon, so I tried [25x25](https://1drv.ms/i/s!AiSfe94wb0vWn5QGEcEoCYYzOcF9hQ?e=GqfLYN), I've currently got it sitting at [30x30](https://1drv.ms/i/s!AiSfe94wb0vWn5QPEpqyGTVNYJ72lA?e=NFYxeI) waiting for it to go down to send the [desaturated](https://1drv.ms/i/s!AiSfe94wb0vWn5QR5pC5k0Rq2oZU5w?e=R5wsBl) version.  You could probably do it better since I'm just messing with your code.

**Comment by I-AM-T3X** [comment]
Thank you for the suggestions! I'm currently under the weather, but as soon as I'm feeling better, I'll review your feedback and see how I can incorporate those changes.

**Comment by I-AM-T3X** [comment]
@fr0z3night would you mind sending me what you currently have. you can send em the excepts or you can upload the entire lua file

**Comment by fr0z3nights** [comment]
Hope you're feeling better, yea sure I had it added to my onedrive sync batch file before just didn't link it, it's [here](https://1drv.ms/f/s!AiSfe94wb0vWn5QF7CcJxVtjyX-Vhg)

**Comment by I-AM-T3X** [comment]
@fr0z3night i just pushed the edits up to github, I'll have the new versions up on curseforge and wago shortly
