### ISSUE TITLE
idea refresh timer

### ISSUE THREAD

**Issue by n0t49a1n** [I-AM-T3X/TokenPriceChecker#2]
![image](https://github.com/user-attachments/assets/ec5e869c-d26d-436a-9cfa-e1b45b1246e8)
i modded your addon 
Add selectable refresh timer (3-12 mins)
Add timer till refresh
Add 24hr(or session) peak on hover

**Comment by I-AM-T3X** [comment]
While I appreciate the suggestion, I won’t be adding this feature to my addon at this time. The current 5-minute interval is a balanced choice, offering timely updates without putting unnecessary strain on the server. During high-demand moments, like the release of the $90 store Brutosaur, we saw how even a popular API call can become overloaded, affecting users and Blizzard's infrastructure. By setting the timer to start based on each player’s login time, the load is naturally spread out, even across tens of thousands of users. This setup minimizes the strain on Blizzard’s servers and reduces the risk of the API being flagged or moved to a protected list, which could restrict or impact its availability for everyone.

That said, if you’d like to modify the code and adjust the timing or features to better suit your needs, feel free to do so! Customizing it locally won’t impact the API in the same way, so you’re welcome to make it your own.
